export const SPLIT_TYPE = Object.freeze({
  EQUAL: 'EQUAL',
  CUSTOM: 'CUSTOM'
});

export const EXPENSE_CATEGORIES = Object.freeze({
  MEDICINE: 'MEDICINE',
  DOCTOR: 'DOCTOR',
  FOOD: 'FOOD',
  GROCERY: 'GROCERY',
  TRANSPORT: 'TRANSPORT',
  BILLS: 'BILLS',
  CAREGIVER: 'CAREGIVER',
  EQUIPMENT: 'EQUIPMENT',
  OTHER: 'OTHER'
});
